### ISSUE TITLE
location of example file

### ISSUE THREAD

**Issue by rturcotte861** [fairSIM/fairSIM#7]

**Comment by mueller-physics** [comment]
Hi,

can you specify which files you are looking for exactly? The raw data sets or the reconstruction parameters?

**Comment by mueller-physics** [comment]
Yes, sorry, the links where missing in the quick-start guide. See https://github.com/fairSIM/fairSIM/blob/v1.0.2/org/fairsim/fiji/TestPlugin.java
for the complete algorithm and https://github.com/fairSIM/fairSIM/blob/v1.0.2/org/fairsim/sim_algorithm/SimAlgorithm.java}
for ready-to-use high level functions (I've also added this as a footnote to the quickstart guide now).

**Comment by rturcotte861** [comment]
Thank you.

There are several ways to get a java plugin, then integrate it into Fiji. Fiji recommends using Maven/Eclipse, but the current FairSIM doesn't have a pom.xml file (it has a makefile instead). What is the best way/compilation tool in order to recompile the fairSIM gui (let's say I don't even want to make edits)? What is the best way to get the TestPlugin.java to run as a .class in ImageJ?  It would be quite helpful if there was a tutorial or if you could point users to an appropriate external tutorial. I followed quite a few tutorials, but none of them can make the TestPlugin.java or a recompile version of fairSIM.jar work in Fiji.

**Comment by mueller-physics** [comment]
Yes, in the future, maven would be ideal to fit in with the Fiji ecosystem. However, it is only required for plugins that are distributed directly with Fiji. Otherwise, just creating a jar file and dropping it into the plugins folder will suffice.

- I develop under Linux (Ubuntu), so the makefile works out-of-the-box for me. After a fresh clone from git, only the ImageJ jar file has to be added to ./external
- Others in my group work under Windows, and use Netbeans. Again this should work out-of-the-box, only the ij-?.??.jar file (found in Fiji.app/jars) is needed as an external dependence for classes beyond standard Java.
- Concerning tutorials, I found https://imagej.net/How_to_contribute_to_an_existing_plugin_or_library and especially https://imagej.net/Developing_ImageJ_in_Eclipse, but I have not tried how well these work.

If you only want to run the "TestPlugin.java" file, and make small changes / macros out of it, you can also use the script editor in Fiji. For this

- Make sure fairSIM.jar is in the plugin folder.
- Copy TestPlugin.java to some folder where you want to edit it.
- Comment out "package org.fairsim.fiji" in line 19, otherwise current versions of the script editor will have trouble with file locations
- Click "run" to compile & run the file

If this does not work, try with a minimal "Hello World" plugin first if your Fiji installation supports compiling Java plugins. There were some troubles with this feature introduced with the switch to Java 1.8, see 
http://forum.imagej.net/t/no-javac-jar-found/2340/2 and https://github.com/fiji/fiji/issues/119#issuecomment-234063994.
